version: "3.8"

services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-success-insights-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./ai_success_insights.db
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-success-insights-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

volumes:
  backend-data:
    driver: local

networks:
  default:
    name: ai-success-insights-network
